### ISSUE TITLE
Not able to run demo

### ISSUE THREAD

**Issue by rajma996** [tianzhi0549/CTPN#16]
I could successfully build, but I am not able to run the demo however, I have used cuda 7.5 and cudnn version 3 as mentioned, but I am getting this error while running the demo .
`
Image: img_1.jpg

F1218 15:10:22.093291  6307 cudnn_conv_layer.cu:85] Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED
*** Check failure stack trace: ***
Aborted (core dumped)
`
I tried resolving it from the issue [here](https://github.com/NVIDIA/DIGITS/issues/232) but I am not able to follow it much. Thanks a lot in advance .

**Comment by tianzhi0549** [comment]
@rajma996 I google for this error and find it may have to do with the version of CUDNN. Please double check that the caffe in this program was compiled with correct CUDNN. And can you run the program without CUDNN? Thank you:-).

**Comment by rajma996** [comment]
@tianzhi0549  Thanks for the reply, I had memory limit error without CUDNN, as the GPU I am using has 4 GB memory. I am sure CUDNN v3 is used while building, I'll check for the demo program . Thanks again .

**Comment by rajma996** [comment]
@tianzhi0549  The issue is resolved now, the library path variable wasn't set properly. Thanks
